- action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.arlo_base
  - condition: state
    entity_id: remote.living_room_harmony
    state: 'off'
  - data:
      activity: Watch TV
      entity_id: remote.living_room_harmony
    service: remote.turn_on
  alias: Someone Comes Home
  condition: []
  id: '1507093785956'
  trigger:
  - entity_id: group.all_devices
    from: not_home
    platform: state
    to: home