- id: '1507093785956'
  alias: Someone Comes Home
  trigger:
  - entity_id: device_tracker.luke_gs9
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      brightness: 255
      entity_id: light.kitchen_bar
    service: light.turn_on
  - data:
      entity_id: alarm_control_panel.arlo_base
    service: alarm_control_panel.alarm_disarm
  - condition: state
    entity_id: remote.living_room
    state: 'off'
  - data:
      activity: Watch TV
      entity_id: remote.living_room
    service: remote.turn_on
  - data:
      away_mode: home
    service: nest.set_away_mode
- id: '1507093785957'
  alias: Everyone Is Away
  trigger:
  - entity_id: device_tracker.luke_gs9
    for: 0:04:00
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: light.kitchen_bar
    service: light.turn_off
  - data:
      entity_id: remote.living_room
    service: remote.turn_off
  - data:
      entity_id: alarm_control_panel.arlo_base
    service: alarm_control_panel.alarm_arm_away
  - data:
      away_mode: away
    service: nest.set_away_mode
  hide_entity: true
- id: '1507093785958'
  alias: Home Assistant Startup
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  condition: []
  action:
    service: notify.push
    data:
      message: Home Assistant started.
