# Turn on patio lights at sunset
- alias: 'Turn On Patio Lights At Sunset'
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    - service: switch.turn_on
      entity_id: switch.ge_patio_switch_switch

# Turn off patio lights at sunrise
- alias: 'Turn Off Patio Lights At Sunrise'
  hide_entity: True
  trigger:
    platform: sun
    event: sunrise
    offset: "-01:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.ge_patio_switch_switch

# Turn patio camera off when outside
- alias: 'Turn off cameras when door is open'
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.zwone_patio_door
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.galaxy_s9
    state: 'home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.arlo_base

# Turn patio camera on when door shuts
- alias: 'Turn on camera when door closes'
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.zwone_patio_door
    to: 'off'
  condition:
    condition: state
    entity_id: device_tracker.galaxy_s9
    state: 'home'
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.arlo_base

# Everyone leaves
- alias: 'Everyone Is Away'
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.all_devices
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 3
      seconds: 0
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.arlo_base
    - service: remote.turn_off
      entity_id: group.all_remotes
    - service: switch.turn_off
      entity_id: group.lights
    - service: light.turn_off
      entity_id: group.lights

# Notify when HASS starts up
- alias: 'Home Assistant Startup'
  hide_entity: True
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.push
    data:
      message: Home Assistant started.

# Announce when door opens
- alias: 'Announce Door Open'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.zwtwo_front_door
        - binary_sensor.zwone_patio_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: cover.truck_garage_door
      from: 'closed'
      to: 'open'
  action:
    - service: tts.google_say
      entity_id: media_player.googlehome9280
      data_template:
        message: '{{ trigger.to_state.name }} opened'

# Notify when a door opens when nobody is home
- alias: 'Notify When Door Opens While Everyone is Away'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.zwtwo_front_door
        - binary_sensor.zwone_patio_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: cover.truck_garage_door
      to: 'open'
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'not_home'
  action:
    service: notify.push
    data_template:
      message: '{{ trigger.to_state.name }} opened while everyone is away at {{ as_timestamp(now()) | timestamp_custom("%m-%d-%Y %I:%M:%S %p", true) }}'

# Run roomba every day at noon
- alias: Run Roomba
  trigger:
    - platform: time
      at: '12:00:00'
  action:
    service: vacuum.turn_on
    entity_id: vacuum.roomba