- id: '1507093785956'
  alias: Someone Comes Home
  trigger:
  - entity_id: device_tracker.luke_s9
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: light.kitchen_bar
    service: light.turn_on
  - condition: state
    entity_id: remote.living_room
    state: 'off'
  - data:
      activity: Watch TV
      entity_id: remote.living_room
    service: remote.turn_on
- id: '1507093785957'
  alias: Everyone Is Away
  trigger:
  - entity_id: device_tracker.luke_s9
    for:
      hours: 0
      minutes: 4
      seconds: 0
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - entity_id: group.all_remotes
    service: remote.turn_off
  - entity_id: group.lights
    service: light.turn_off
  hide_entity: true
- id: '1507093785958'
  alias: Home Assistant Startup
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  condition: []
  action:
    service: notify.push
    data:
      message: Home Assistant started.
