homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 213
  unit_system: imperial
  time_zone: America/Chicago
  customize:
    device_tracker.laptopol7di05q:
      hidden: true
    device_tracker.samsung_soundbar_jseries:
      hidden: true
    media_player.bedroom:
      friendly_name: Bedroom Chromecast
    media_player.living_room:
      friendly_name: Living Room Chromecast
    sensor.yr_temperature:
      friendly_name: Outside Temp
    sensor.yr_precipitation:
      friendly_name: Precip
    zwave.sigma_designs_uzb_zwave_usb_adapter:
      friendly_name: Z-Wave Controller
    switch.ge_patio_switch_switch:
      friendly_name: Patio Switch
    switch.wemo_switch:
      friendly_name: Office Lamp
    sensor.living_room_thermostat_humidity:
      friendly_name: Nest Humidity
    sensor.living_room_thermostat_target:
      friendly_name: Nest Target
    sensor.living_room_thermostat_temperature:
      friendly_name: Nest Temp
    binary_sensor.patio_sensor_patio:
      friendly_name: Patio Door
    binary_sensor.front_door_sensor_sensor:
      friendly_name: Front Door
    light.centralite_4257050rzhac_04483b08_1:
      friendly_name: Bedroom Lamp

  customize_glob:
    "binary_sensor.*":
      device_class: opening
    "media_player.*":
      icon: mdi:filmstrip
    "remote.*":
      icon: mdi:remote
    "sensor.patio_sensor_*":
      hidden: true
    "sensor.front_door_sensor*":
      hidden: true

config:
conversation:
discovery:
  ignore:
    - samsung_tv
frontend:
history:
logbook:
sun:
updater:

http:  
  api_password: !secret api_password

notify:
  - platform: pushbullet
    name: push
    api_key: !secret pushbullet_key

tts:
  platform: google

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - precipitation

mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_broker_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - humidity
      - temperature
      - target
  binary_sensors:
    monitored_conditions:

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

device_tracker:
  - platform: owntracks
  - platform: bluetooth_tracker
    interval_seconds: 10

#################
#	INCLUDES	#
#################

alert: !include alerts.yaml
automation: !include automations.yaml
automation old: !include automations_old.yaml
group: !include groups.yaml
remote: !include remotes.yaml
script: !include scripts.yaml
zone: !include_dir_list zones/