homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 213
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*":
      device_class: opening
    "media_player.*":
      icon: mdi:filmstrip
    "remote.*":
      icon: mdi:remote
    "sensor.patio_sensor_*":
      hidden: true
    "sensor.front_door_sensor*":
      hidden: true
config:
conversation:
discovery:
  ignore:
    - samsung_tv
frontend:
history:
logbook:
sun:
updater:

http:  
  api_password: !secret api_password

notify:
  - platform: pushbullet
    name: push
    api_key: !secret pushbullet_key

tts:
  platform: google

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

# INCLUDES
alert: !include alerts.yaml
automation: !include automations.yaml
automation old: !include automations_old.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_trackers.yaml
group: !include groups.yaml
mqtt: !include mqtt.yaml
nest: !include nest.yaml
remote: !include remotes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
vacuum: !include vacuums.yaml
zone: !include_dir_list zones/