homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 213
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*":
      device_class: opening
    "media_player.*":
      icon: mdi:filmstrip
    "remote.*":
      icon: mdi:remote
    "sensor.patio_sensor_*":
      hidden: true
    "sensor.front_door_sensor*":
      hidden: true
config:
conversation:
discovery:
  ignore:
    - samsung_tv
    - directv
    - harmony
frontend:
history:
logbook:
sun:
updater:
  include_used_components: true
hassio:
recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - group
      - script

http:  
  api_password: !secret api_password
  server_port: !secret hass_port
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

notify:
  - platform: pushbullet
    name: push
    api_key: !secret pushbullet_key
  - platform: lannouncer
    name: lan
    host: !secret lannouncer_ip

tts:
  platform: google
  time_memory: 57600

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

panel_iframe:
  configurator:
    title: Edit
    icon: mdi:wrench
    url: !secret configurator_url

hue:
  bridges:
    - host: !secret hue_ip

weblink:
  entities:
    - name: Arlo
      url: 'https://arlo.netgear.com/#/cameras'
      icon: mdi:cctv
    - name: Ring
      url: 'https://ring.com/account/activity'

ffmpeg:

arlo:
  username: !secret arlo_un
  password: !secret arlo_pw

alarm_control_panel:
  - platform: arlo
    home_mode_name: Home

#camera:
  #- platform: arlo
  #- platform: ring

ring:
  username: !secret ring_un
  password: !secret ring_pw

namecheapdns:
  host: !secret namecheap_host_1
  domain: !secret namecheap_domain_1
  password: !secret namecheap_password_1

rest_command:
  sleep_pc:
    url: !secret sleep_on_lan_url

# INCLUDES
alert: !include alerts.yaml
automation: !include automations.yaml
automation old: !include automations_old.yaml
binary_sensor: !include binary_sensors.yaml
cover: !include covers.yaml
cloud: !include cloud.yaml
device_tracker: !include device_trackers.yaml
fan: !include fans.yaml
group: !include groups.yaml
#nest: !include nest.yaml
remote: !include remotes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
vacuum: !include vacuums.yaml
zone: !include_dir_list zones/