homeassistant:
  name: Home
  external_url: !secret base_url
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 213
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob:
    "media_player.*":
      icon: mdi:filmstrip
    "remote.*":
      icon: mdi:remote

config:
system_health:
cloud:
discovery:
  ignore:
    - harmony
frontend:
history:
logbook:
  exclude:
    entities:
      - sensor.time_formatted
recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - group
      - script

sun:

http:
  server_port: !secret hass_port
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10

tts:
  - platform: google_translate
    service_name: google_say

#hue:
#  bridges:
#    - host: !secret hue_ip

#aarlo:
#  username: !secret arlo_un
#  password: !secret arlo_pw

#alarm_control_panel:
#  - platform: aarlo
#    home_mode_name: Home
#    alarm_volume: 5

#camera:
#  - platform: aarlo

cover:
lovelace:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# ===================== INCLUDES =====================
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_trackers.yaml
group: !include groups.yaml
#fan: !include fans.yaml
#nest: !include nest.yaml
#remote: !include remotes.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include_dir_list zones/