homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 213
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*":
      device_class: opening
    "media_player.*":
      icon: mdi:filmstrip
    "remote.*":
      icon: mdi:remote
    "sensor.patio_sensor_*":
      hidden: true
    "sensor.front_door_sensor*":
      hidden: true
config:
conversation:
discovery:
  ignore:
    - samsung_tv
frontend:
history:
logbook:
sun:
updater:

http:  
  api_password: !secret api_password

notify:
  - platform: pushbullet
    name: push
    api_key: !secret pushbullet_key

tts:
  platform: google

binary_sensor:
  - platform: template
    sensors:
      roomba_bin_full:
        friendly_name: Roomba Bin Full
        value_template: "{{ states.vacuum.roomba.attributes.bin_full }}"

sensor:
  - platform: darksky
    api_key: 939be94166978a1c4320e310b90d3ef0
    units: us
    monitored_conditions:
      - precip_type
      - precip_intensity
      - temperature
      - nearest_storm_distance
      - humidity
  - platform: template
    sensors:
      roomba_battery:
        friendly_name: Roomba Battery
        unit_of_measurement: "%"
        value_template: "{{ states.vacuum.roomba.attributes.battery_level }}"
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_broker_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - humidity
      - temperature
      - target
  binary_sensors:
    monitored_conditions:

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

device_tracker:
#  - platform: owntracks
  - platform: bluetooth_tracker
    interval_seconds: 15

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_un
    password: !secret roomba_pw

#################
#	INCLUDES	#
#################

alert: !include alerts.yaml
automation: !include automations.yaml
automation old: !include automations_old.yaml
group: !include groups.yaml
remote: !include remotes.yaml
script: !include scripts.yaml
zone: !include_dir_list zones/