homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: 213
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*":
      device_class: opening
    "media_player.*":
      icon: mdi:filmstrip
    "remote.*":
      icon: mdi:remote
    "sensor.patio_sensor_*":
      hidden: true
    "sensor.front_door_sensor*":
      hidden: true

config:
system_health:
cloud:
discovery:
  ignore:
    - samsung_tv
    - directv
    - harmony
frontend:
history:
logbook:
recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - group
      - script
    entities:
      - sensor.ecolink_doorwindow_sensor_access_control
      - sensor.ecolink_doorwindow_sensor_alarm_level
      - sensor.ecolink_doorwindow_sensor_alarm_type
      - sensor.ecolink_doorwindow_sensor_burglar
      - sensor.ecolink_doorwindow_sensor_power_management
      - sensor.ecolink_doorwindow_sensor_sourcenodeid
sun:
updater:
  include_used_components: true

http:
  server_port: !secret hass_port
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

tts:
  - platform: google_translate
    service_name: google_say

zwave:
  usb_path: /dev/ttyUSB0

hue:
  bridges:
    - host: !secret hue_ip

rest_command:
  sleep_pc:
    url: !secret sleep_on_lan_url

arlo:
  username: !secret arlo_un
  password: !secret arlo_pw

alarm_control_panel:
  - platform: arlo
    home_mode_name: Home
    scan_interval: 120

namecheapdns:
  host: !secret namecheap_host_1
  domain: !secret namecheap_domain_1
  password: !secret namecheap_password_1

# ===================== INCLUDES =====================

alert: !include alerts.yaml
automation: !include automations.yaml
automation old: !include automations_old.yaml
binary_sensor: !include binary_sensors.yaml
cover: !include covers.yaml
device_tracker: !include device_trackers.yaml
fan: !include fans.yaml
group: !include groups.yaml
notify: !include notify.yaml
remote: !include remotes.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
weblink: !include weblinks.yaml
vacuum: !include vacuums.yaml
zone: !include_dir_list zones/
