- platform: version
  name: version_available
  source: hassio
  image: raspberrypi3
- platform: version
  name: version_current
  source: local
- platform: darksky
  api_key: !secret darksky_api_key
  units: us
  monitored_conditions:
    - temperature
    - humidity
- platform: history_stats
  name: Roomba Runtime Today
  entity_id: vacuum.t2
  state: 'cleaning'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Living Room TV On Today
  entity_id: remote.living_room
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: template
  sensors:
    xiaomi_temp:
      friendly_name: Living Room Temp
      unit_of_measurement: '°F'
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.temperature * 9/5 + 32|round(2) }}"
    xiaomi_air_quality:
      friendly_name: Air Quality
      unit_of_measurement: 'PM2.5'
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.aqi }}"
    roomba_battery:
      friendly_name: Roomba Battery
      unit_of_measurement: "%"
      value_template: "{{ states.vacuum.t2.attributes.battery_level }}"
    roomba_status:
      friendly_name: Roomba Status
      value_template: "{{ states.vacuum.t2.attributes.status }}"