- platform: darksky
  api_key: !secret darksky_api_key
  units: us
  monitored_conditions:
    - summary
    - icon
    - temperature
    - humidity
    - wind_speed
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_probability
    - precip_accumulation
    - precip_intensity
- platform: history_stats
  name: Roomba Runtime Today
  entity_id: vacuum.t2
  state: 'cleaning'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Living Room TV On Today
  entity_id: remote.living_room
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: template
  sensors:
    roomba_battery:
      friendly_name: Roomba Battery
      unit_of_measurement: "%"
      value_template: "{{ states.vacuum.t2.attributes.battery_level }}"
    roomba_status:
      friendly_name: Roomba Status
      value_template: "{{ states.vacuum.t2.attributes.status }}"
- platform: template
  sensors:
    time_formatted:
      friendly_name: "Date and time"
      value_template: "{{ now() }}"
      icon_template: mdi:calendar-clock
      attribute_templates:
        date: "{{ as_timestamp(now()) | timestamp_custom('%m/%d/%Y') }}"
        time: "{{ as_timestamp(now()) | timestamp_custom('%I:%M %p') }}"