- platform: darksky
  api_key: !secret darksky_api_key
  units: us
  monitored_conditions:
    - precip_type
    - temperature
    - nearest_storm_distance
    - humidity
- platform: history_stats
  name: Roomba Runtime Today
  entity_id: vacuum.roomba
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Bedroom TV On Today
  entity_id: remote.bedroom_harmony
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Living Room TV On Today
  entity_id: remote.living_room_harmony
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: template
  sensors:
    roomba_battery:
      friendly_name: Roomba Battery
      unit_of_measurement: "%"
      value_template: "{{ states.vacuum.roomba.attributes.battery_level }}"
    roomba_status:
      friendly_name: Roomba Status
      value_template: "{{ states.vacuum.roomba.attributes.status }}"
