- platform: darksky
  api_key: !secret darksky_api_key
  units: us
  monitored_conditions:
    - precip_type
    - temperature
    - nearest_storm_distance
    - humidity
- platform: history_stats
  name: Roomba Runtime Today
  entity_id: vacuum.roomba
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Living Room TV On Today
  entity_id: remote.living_room
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: template
  sensors:
    xiaomi_temp:
      friendly_name: Living Room Temp
      unit_of_measurement: '°F'
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.temperature * 9/5 + 32 }}"
    xiaomi_air_quality:
      friendly_name: Air Quality
      unit_of_measurement: 'PM2.5'
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.aqi }}"
    roomba_battery:
      friendly_name: Roomba Battery
      unit_of_measurement: "%"
      value_template: "{{ states.vacuum.roomba.attributes.battery_level }}"
    roomba_status:
      friendly_name: Roomba Status
      value_template: "{{ states.vacuum.roomba.attributes.status }}"
    truck_garage_status:
      friendly_name: 'Truck Door Status'
      value_template: '{% if states.cover.truck_garage_door %}
          {% if states.cover.truck_garage_door.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.truck_garage_door.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.truck_garage_door.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.truck_garage_door.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
    garage_car_present:
      friendly_name: 'Truck in Garage'
      value_template: '{% if states.cover.truck_garage_door %}
          {% if states.cover.truck_garage_door.state == "open" %}
            n/a
          {% elif ((states.cover.truck_garage_door.attributes["distance_sensor"] > 40) and (states.cover.truck_garage_door.attributes["distance_sensor"] < 150)) %}
            Yes
          {% else %}
            No
          {% endif %}
          {% else %}
          n/a
          {% endif %}'