sensor.ecolink_doorwindow_sensor_access_control_2:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_alarm_level_2:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_alarm_type_2:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_burglar_2:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_sourcenodeid_2:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_access_control:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_burglar:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_power_management:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.ecolink_doorwindow_sensor_power_management_2:
  ignored: true
  polling_intensity: 0
